name: test

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Compiling
        run: npx tsc
      
      - name: Running Tests
        run: node dist/main.js


